name: todo_list
description: TODO List - example of using Flutter and Firebase

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.2.0
  firebase_auth: 4.1.2
  provider: 6.0.4
  cloud_firestore: 4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/facebook_logo.png
    - images/google_logo.png
